#parentheses-ფრჩხილები
#quatation quotes - ბრჭყალები
print("apple")
print("dog")
print("group84")
print("coding")
print("chatting")
print("calling")
print("workingout")
print("sunset")
print("galaxy")
print("mountain")
print("cactus")
print("nebula")
print("thunder")
print("bubble")
print("ocean")
print("pumpkin")
print("dream")
print("shadow")
print("mirror")
print("the end of homework")